# GitHub Pages
# None of these can actually be changed
safe:     true
lsi:      false
highlighter: pygments

# Formatting
markdown: redcarpet
redcarpet:
  extensions: [
    "autolink"
  , "tables"
  , "strikethrough"
  , "with_toc_data"
  , "fenced_code_blocks"
  , "no_intra_emphasis"
  ]

# Permalinks
permalink: pretty

# File inclusion (these would otherwise be hidden)
include: ["_assets", "_search.json"]

exclude: [CNAME, Gemfile, Gemfile.lock, Makefile, README.md, LICENSE, vendor, robots_*, linklint]

# Project specific
# Remember to change these!
baseurl:
title:        bringmeister
tagline:      The developer guides to api time capacity
description:
url:          http://api.time-capacity.bringmeister.de

author:
  name:       Thomas Wiener
  url:        https://github.com/thomaswiener

bringmeister:
  url:        https://bringmeister.de
  api:        https://api.bringmeister.de/v1
